import Head from 'next/head'
import Header from '../components/nav/header'
import withUsers from './withUsers'


const Home = ({userExpert, clients, notifications}) => {

  return (
    <div>
      <Head>
        <title>Talents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header userExpert={userExpert} clients={clients} preloadNotifications={notifications}></Header>
      <div className="home">
        <div className="home-card-container">
          <div className="home-card-item">
            <img src="https://patch.com/img/cdn20/users/22872998/20200205/113840/styles/patch_image/public/bartender___05233528487.png" alt="" />
            <div className="home-card-item-title">Hire the best talent for your events</div>
            <div className="home-card-item-description">Take your events to the next level! Birthdays, large receptions, team building, tastings, name it we have the one for you</div>
          </div>
          <div className="home-card-item">
            <img src="https://www.insurancejournal.com/app/uploads/2021/03/waiter-scaled.jpg" alt="" />
            <div className="home-card-item-title">Profits to the moon</div>
            <div className="home-card-item-description">Beverage is crucial for a succesful business, get support from a professional for your beverage program, staff training etc..</div>
          </div>
          <div className="home-card-item">
            <img src="https://beyondcurated.com/wp-content/uploads/2019/07/The-Art-Of-The-Sommelier.jpg" alt="" />
            <div className="home-card-item-title">Private wine cellar and Bar consulting</div>
            <div className="home-card-item-description">Get advise from the best sommelier and mixologiest to build your Winne cellar and you bar for investments or just joyce</div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default withUsers(Home)

